---
- name: deployment servers
  hosts: uat
  remote_user: ubuntu
  become: true

  tasks:
  - name: copy application jar
    copy: src=../target/spring-boot-hello-world-0.0.1-SNAPSHOT.jar dest=deployable/
  
  - name: start application service
    command: sudo systemctl start spring-boot-hello-world.service
